all:
	make blackboard
	make eventbus
	make pipesandfilters
blackboard:
	g++ Blackboard.cpp --std=c++14 -o blackboard.exe
	./blackboard.exe

eventbus:
	g++ EventBus.cpp --std=c++14 -o eventbus.exe
	./eventbus.exe

pipesandfilters:
	g++ PipesAndFilters.cpp --std=c++14 -o pipesandfilters.exe
	./pipesandfilters.exe
